### ISSUE TITLE
Malemute large wheels default to having shock horizontal (will not drive that way)

### ISSUE THREAD

**Issue by Skavin** [BobPalmer/Malemute#10]
when a new large wheel is created in the SPH they default to having shock horizontal
the wheel attaches and looks sort of ok in the SPH

when launched the wheels spin but the malemute does not move.

defaulting the wheels to have the shock vertical in the SPH would make building a melemute a little less confusing the first time

**Comment by BobPalmer** [comment]
This is pretty much how all stock wheels are in the SPH, because of how wheels work.
