### ISSUE TITLE
Request: Connected Living Space configs

### ISSUE THREAD

**Issue by StarkRG** [BobPalmer/Malemute#20]
I'm really loving this new, smaller rover, but it'd be nice if it could integrate into the rest of my connected living space parts (especially when docked).

**Comment by BobPalmer** [comment]
I'd happily take a pull request for this.

**Comment by kjnicoletti** [comment]
You already did :) 

https://github.com/BobPalmer/Malemute/commit/5b5a5e866253464edc372631ded80b0987c0131b
